[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1.38.0"
axum = "0.7.5"
surrealdb = "1.5.3"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
once_cell = "1.19.0"
futures = "0.3.30"
serde = "1.0.203"
